### ISSUE TITLE
Unable to post comments on eLearning platform

### ISSUE THREAD

**Issue by brankobog** [MilanStarcevic/SecureSoftwareDevelopment#4]
Obaveštenje na eLearning platformi kaze:
> Možete ostaviti nalog u komentarima na ovu temu. 

Iz nekog razloga ne mogu da ostavim komentar na pomenutu temu (mozda nemam prava) pa se javljam ovde. Slobodno zatvorite ovaj issue.

Pozdrav,
Branko Bogdanovic - br ind. 3372/19

**Comment by MilanStarcevic** [comment]
Hvala puno na obaveštenju!

**Comment by zilsKS** [comment]
@MilanStarcevic, @madicd   Arsic Zivorad 3137/19 username: zilsKS

**Comment by Cilukes** [comment]
@MilanStarcevic @madicd 
Username: 
Cilukes

**Comment by vladimir-siv** [comment]
@MilanStarcevic @madicd Vladimir Sivčev 3172/19m (vladimir-siv)

**Comment by pedjamitrovic** [comment]
@MilanStarcevic  @madicd 
Predrag Mitrović 2019/3173 - pedjamitrovic

**Comment by aksabg** [comment]
Aleksa Radovanović 2019/3053 - aksabg

**Comment by MiodragMilosevic** [comment]
Miodrag Milosevic 2019/3170 - MiodragMilosevic

**Comment by KovacStefan** [comment]
Stefan Kovač 3218/2019 KovacStefan

**Comment by dusanc** [comment]
dusanc
Dušan Cerovac 2019/3429

**Comment by dm193421m** [comment]
Milena Djelevic 2019/3421-dm193421m

**Comment by golubovicaleksandar** [comment]
Aleksandar Golubovic 2019/3306

**Comment by aleksandargolubovic** [comment]
Aleksandar Golubovic 2019/3306

**Comment by dzoni996** [comment]
Dodov Nikola 2019/3187 (dn193187m)

**Comment by dajana72** [comment]
Dajana Yasir 2019/3043 - dajana72

**Comment by simka1911** [comment]
simka1911 - Katarina Simic, 2019/3473, sk193473m

**Comment by KnezevicIvana** [comment]
@MilanStarcevic @madicd  
KnezevicIvana  - Ivana Knežević 2019/3069

**Comment by ziza1995** [comment]
ziza1995 - Zeljko Markovic 2018/3114

**Comment by maj3stev** [comment]
Milica Stevanović 3233/2019
Username: maj3stev

**Comment by Jelena96s** [comment]
@MilanStarcevic, @madicd

username: Jelena96s

Jelena Stevanovic 3227/2019

**Comment by MarkoMilojevic** [comment]
Marko Milojevic 2019/3374

**Comment by anastar** [comment]
Ana Stevanovic 2019/3234
username: anastar

**Comment by matijalukic** [comment]
Matija Lukic 19/3279
Username: matijalukic

**Comment by miloskesegic** [comment]
Milos Kesegic 3351/19
Username : miloskesegic

**Comment by mladjanmih** [comment]
Mladjan Mihajlovic: 3047/19
Username: mladjanmih

**Comment by ilijami** [comment]
Ilija Miljkovic 3051/19
Username: ilijami

**Comment by blackdonatello351** [comment]
Ivan Milenkovic 3299/19
Username: blackdonatello351

**Comment by JoannisAr** [comment]
Joannis Aretakis 3217/19
username: JoannisAr

**Comment by MilanStarcevic** [comment]
Closing, since this was resolved.
